name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build bddisasm and bdshemu
      run: make -j$(nproc)
    - name: Install rapidjson
      uses: actions/checkout@master
      with:
        repository: Tencent/rapidjson
        path: rapidjson
    - name: Build dependencies
      run: |
        cd rapidjson
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        sudo make install
        cd ..
        cd ..
    - name: Build disasmtool_lix
      run: |
        cd disasmtool_lix
        mkdir _build
        cd _build
        cmake ..
        make -j$(nproc)
        cd ..
        cd ..
    - name: Install setuptools
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools
    - name: Build pydis
      run: |
        cd pydis
        python3 setup.py build
        cd ..
